weights: yolov5n.pt
cfg: models/yolov5n_kaist-rgbt.yaml
data: data/kaist-rgbt.yaml
hyp:
  lr0: 0.005
  lrf: 0.2
  momentum: 0.937
  weight_decay: 0.0001
  warmup_epochs: 5.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.1
  cls: 0.5
  cls_pw: 1.0
  obj: 1.5
  obj_pw: 1.0
  iou_t: 0.5
  anchor_t: 4.0
  fl_gamma: 1.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 10.0
  translate: 0.2
  scale: 0.6
  shear: 5.0
  perspective: 0.001
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.1
  copy_paste: 0.1
epochs: 30
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: true
noautoanchor: false
noplots: false
evolve: 300
evolve_population: data/hyps
resume_evolve: null
bucket: ''
cache: null
device: '0'
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: pedestrian
name: taehun_val
exist_ok: false
quad: true
cos_lr: false
label_smoothing: 0.0
patience: 100
save_period: -1
seed: 0
local_rank: -1
rgbt: true
entity: taehontas
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: pedestrian/taehun_val
